DeveloperAcademy-POSTECH/toGather

ToGather/ToGather.xcodeproj/project.pbxproj
ToGather/ToGather.xcodeproj/project.xcworkspace/contents.xcworkspacedata
ToGather/ToGather.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
ToGather/ToGather/Assets.xcassets/AccentColor.colorset/Contents.json
ToGather/ToGather/Assets.xcassets/AppIcon.appiconset/Contents.json
ToGather/ToGather/Assets.xcassets/Contents.json
ToGather/ToGather/ContentView.swift
ToGather/ToGather/Preview Content/Preview Assets.xcassets/Contents.json
ToGather/ToGather/ToGatherApp.swift

- 빈 프로젝트 생성
- SwiftLint 적용
폴더링

[ADD] 초기 프로젝트 세팅 및 SwiftLint 적용

---

.gitattributes
ToGather/ToGather/Product.swift

해당 PR과 관련된 이슈를 링크해주세요.
작업 내용과 이미지를 첨부해주세요.
- gitatrributes 추가
- Model 형식 변경 (productPrice의 형식 String -> Double)
리뷰가 필요한 포인트와 해당 되는 커밋을 링크로 걸어주세요.
PR 과정에서 생긴 질문을 적어주세요.

[Add] gitattributes

---

ToGather/ToGather.xcodeproj/project.pbxproj

해당 PR과 관련된 이슈를 링크해주세요.
- FirebaseStorage 패키지 추가 (#10 에서 까먹고 못함)

[ADD] Add firebaseStorage package

---

ToGather/ToGather.xcodeproj/project.pbxproj
ToGather/ToGather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

PinCode 구현을 위해 Swift PM에서 SwiftUI-Introspect 설치

[ADD] Add SwiftUI-Introspect package

---

ToGather/ToGather/Screens/Main/View/MainView.swift

- 커밋,푸쉬 수정 반영이 안되서 다시 PR요청
-  ZStack & HStack 제거 

[Chore] ZStack & VStack delete

---

ToGather/ToGather.xcodeproj/project.pbxproj

#36 
불필요한 SDK 삭제
firebase나 introspect에서 에러 발생시 Package resolve로 해결
Approve만 해주시면 됩니다.

[Fix] 중복된 파이어베이스 SDK 제거, 불필요함 #36

---

ToGather/.swiftlint.yml
ToGather/ToGather.xcodeproj/project.pbxproj

- .swiftlint.yml 추가
- trailing_whitespace 룰 제외
- identifier_name 룰 제외 (변수 이름이 4자 이하이면 에러남)
- .build 파일 excluded에 추가
- .swiftlint.yml 파일 적용 여부

[FIX] .swiftlint.yml 추가

---

ToGather/ToGather/Global/Service/TimeLogic.swift
ToGather/ToGather/Global/Service/UserViewModel.swift
ToGather/ToGather/Models/Saving.swift
ToGather/ToGather/Screens/ProgressCircle/DummyData.swift

- Saving 객체를 수정 : 테스트 용이하도록 초기화 함수 추가, 이제까지 저축금액, 목표저축 금액 변수 추가
- 주석제거, 오타수정

Saving struct 객체 수정

---

ToGather/ToGather.xcodeproj/project.pbxproj
ToGather/ToGather/Global/Extension/Color+Extension.swift
ToGather/ToGather/Global/Literal/Constants.swift
ToGather/ToGather/Global/Service/UserViewModel.swift
ToGather/ToGather/Global/UIComponent/CheckboxToggleStyle.swift
ToGather/ToGather/Screens/Main/View/MainView.swift
ToGather/ToGather/Screens/Setting/View/DisplayModeView.swift
ToGather/ToGather/Screens/Setting/View/SettingView.swift
ToGather/ToGather/Screens/ToGatherApp.swift

- #84 
- 설정창 UI
- user데이터와 닉네임, ID 연결
- 디스플레이모드
- 메인뷰 연결

[FEAT] 설정창 UI & 기능구현

---

ToGather/ToGather/Global/Service/MoneyLogic.swift
ToGather/ToGather/Global/Service/TimeLogic.swift
ToGather/ToGather/Global/Service/UserViewModel.swift
ToGather/ToGather/Screens/Main/View/MainView.swift
ToGather/ToGather/Screens/SavingRecord/View/SavingRecordView.swift
ToGather/ToGather/Screens/SavingStatus/View/SavingStatusView.swift
ToGather/ToGather/Screens/ToGatherApp.swift

[Feat] 메인뷰에 userViewModel 연결하기 & 하드코딩된 부분 수정하기

---

ToGather/ToGather/Screens/ProgressCircle/MyProgressCircle.swift
ToGather/ToGather/Screens/SettingPeriod/SettingPeriod.swift

- UI : 바깥쪽 서클(빨간색 라인) 그리도록 수정
- settingPeriodView의 "다음 버튼" 위치를 위로 조정
- settingPeriodView에서 에셋 컬러 적용

[feat] 간단한 UI 수정

---

ToGather/ToGather.xcodeproj/project.pbxproj
ToGather/ToGather.xcodeproj/xcshareddata/xcschemes/ToGather.xcscheme
ToGather/ToGather/Screens/SavingRecord/View/ImagePicker.swift
ToGather/ToGather/Screens/SavingRecord/View/SavingRecordView.swift
ToGather/ToGather/Screens/ToGatherApp.swift

- #62 
현재 MainView 작업으로 인해 아래 작업은 다른 PR로 보낼 예정
- X 버튼에 의한 modal 뷰 dismiss
- 이번주 저축 완료하기 버튼에 의한 FireStore에 image 저장

저축 기록화면 - 사진 불러오기 및 사진 존재 여부에 따른 제어

---

ToGather/ToGather/Screens/Main/View/MainView.swift
ToGather/ToGather/Screens/Main/ViewModel/MainViewModel.swift
ToGather/ToGather/Screens/SavingRecord/View/SavingRecordView.swift
ToGather/ToGather/Screens/SavingStatus/View/SavingStatusView.swift

초록색 라인 : 기존 연결된 뷰
보라색 라인 : 이번 pr에 연결한 뷰

[feat] 저축 기록화면, 친구 상세페이지 네비게이션 연결

---

ToGather/ToGather/Screens/FriendAddition/View/FriendAdditionView.swift
ToGather/ToGather/Screens/SettingPeriod/SettingPeriod.swift

#91 
navigation link 대상이 되는 view에 title 지정 및 displaymode inline으로 설정 
나중에 추가하기 버튼에 navigation link 설정
navigation title을 inline으로 바꾸는 방법외에 더 나은 방법이 있는지 체크
-  상세페이지 사진 가져오기

[Fix] Navigation back 버튼 안보이는 현상 수정

---

ToGather/ToGather/Global/Service/TimeLogic.swift
ToGather/ToGather/Global/Service/UserViewModel.swift
ToGather/ToGather/Models/Product.swift
ToGather/ToGather/Models/Saving.swift
ToGather/ToGather/Screens/Main/View/MainView.swift
ToGather/ToGather/Screens/ProgressCircle/MyProgressCircle.swift
ToGather/ToGather/Screens/SavingStatus/View/SavingStatusView.swift

- 연도에 . 붙여서 표기 20220603 -> 2022.06.03
- 잘못된 totalWeek 계산 로직 수정
- 더미데이터에 들어가는 이미지 url을 에셋에 있는 이름으로 수정
- weekInfo[0..<currentWeek] 오류 뜨는 부분을 해결

[fix] 1차 버그 수정

---

ToGather/ToGather/Screens/FriendAddition/View/PinStackView.swift

#97 
맞은 아이디에 관해서 shaking 되는 현상 해결

[Fix] 맞은 아이디 grid shaking 버그 수정

---

ToGather/ToGather/Models/Saving.swift
ToGather/ToGather/Screens/FriendAddition/View/FriendAdditionView.swift
ToGather/ToGather/Screens/ProgressCircle/MyProgressCircle.swift

- 메인뷰에서 친구 퍼센트 잘못 나오는 오류 수정
- 메인뷰에서 친구 추가할 경우 온보딩 마지막 페이지로 가지 않도록 수정
- totalFailedNum 초기 1 세팅되어 있는 것 수정

[fix] 버그수정 2

---

ToGather/ToGather/Screens/SavingStatus/View/SavingStatusView.swift

[Feat] 상세저축 페이지 수정 

---

ToGather/ToGather/Global/Service/UserViewModel.swift
ToGather/ToGather/Models/Saving.swift
ToGather/ToGather/Screens/Main/View/MainView.swift
ToGather/ToGather/Screens/Main/ViewModel/MainViewModel.swift
ToGather/ToGather/Screens/ProgressCircle/DummyData.swift

[fix] 데모를 위한 수정

---

ToGather/ToGather/Global/Service/FirebaseManager.swift
ToGather/ToGather/Screens/Main/View/MainView.swift
ToGather/ToGather/Screens/SavingStatus/View/SavingStatusView.swift

[Feat] 파이어베이스 이미지 가져오기 함수

---

ToGather/ToGather.xcodeproj/project.pbxproj
ToGather/ToGather/Global/Service/CustomNavigationLink.swift
ToGather/ToGather/Screens/FriendAddition/View/FriendAdditionView.swift
ToGather/ToGather/Screens/GoalSetting/View/GoalSetting.swift
ToGather/ToGather/Screens/SettingPeriod/SettingPeriod.swift

커스텀 백버튼을 바로 사용할 수 있는 CustomNavigationLnik 구현
사용법은 NavigationLink와 동일

네비게이션 뷰에 custom 백버튼을 적용

---

README.md

[docs] README.md 소개 추가

---

License
README.md

리드미에 저는 실제 사진으로 넣었는데, 실제 사진으로 바꾸고 싶으신분들 있으신가요? 
혹시 통일성 떨어진다고 생각하면 이모지로 바꾸겠습니다.
그리고 폴더링 구조가 좀더 간결하다고 필요하면 수정하겠습니다!

[Docs] 리드미 수정 

---

ToGather/ToGather.xcodeproj/project.pbxproj
ToGather/ToGather/Global/Service/FirebaseManager.swift
ToGather/ToGather/Screens/Core/Main/UIComponent/ProgressCircle/FriendProgressCircle.swift
ToGather/ToGather/Screens/Core/Main/View/MainView.swift
ToGather/ToGather/Screens/Core/Main/ViewModel/MainViewModel.swift
ToGather/ToGather/Screens/Core/SavingRecord/View/SavingRecordView.swift
ToGather/ToGather/Screens/Core/Start/View/StartView.swift
ToGather/ToGather/Screens/Onboarding/FriendAddition/ViewModel/FriendAdditionViewModel.swift
ToGather/ToGather/Screens/Onboarding/GoalSetting/View/GoalSetting.swift
ToGather/ToGather/Screens/Onboarding/LastOnboarding/View/LastOnboardingView.swift
ToGather/ToGather/Screens/Onboarding/SettingPeriod/SettingPeriod.swift
ToGather/ToGather/ViewModels/UserViewModel.swift

firebaseManager, onbordingViewModel에 존재하는 함수명 리팩토링

[Feat] 함수 및 변수명 renaming

---

ToGather/ToGather/Screens/Onboarding/LastOnboarding/View/LastOnboardingView.swift
ToGather/ToGather/Screens/Onboarding/SettingPeriod/SettingPeriod.swift

[Feat] 금액 표시 문구 변경

---

ToGather/ToGather.xcodeproj/project.pbxproj
ToGather/ToGather/Screens/Onboarding/FriendAddition/UIComponent/PersonView.swift
ToGather/ToGather/Screens/Onboarding/FriendAddition/View/AlreadyAddedFriendView.swift
ToGather/ToGather/Screens/Onboarding/FriendAddition/View/FriendAdditionView.swift
ToGather/ToGather/Screens/Onboarding/FriendAddition/ViewModel/FriendAdditionViewModel.swift
ToGather/ToGather/ViewModels/UserViewModel.swift

- 마크 주석 처리 작성
- 서브뷰들 익스텐션으로 코드 수정
- 서브뷰 컴포넌트화
- 관련 코드 그룹핑
- 닉네임 고유아이디로 변경

[CHORE] UserViewModel, FriendAdditionView 및 ViewModel 코드 리팩토링

---

ToGather/ToGather/Models/User.swift
ToGather/ToGather/Screens/Core/Setting/View/SettingView.swift
ToGather/ToGather/ViewModels/UserViewModel.swift

[CHORE] 환경세팅창에서 닉네임을 고유아이디로 변경 

---

ToGather/ToGather/Screens/Core/SavingRecord/View/SavingRecordView.swift

[Feat] 친구에게 알리기 제거

---

ToGather/ToGather/Global/Logic/TimeLogic.swift
ToGather/ToGather/Models/DummyData.swift
ToGather/ToGather/Models/User.swift
ToGather/ToGather/Screens/Core/Main/UIComponent/ProgressCircle/FriendProgressCircle.swift
ToGather/ToGather/Screens/Core/Main/UIComponent/ProgressCircle/MyProgressCircle.swift
ToGather/ToGather/Screens/Core/Main/UIComponent/ProgressCircle/ProgressCircle.swift
ToGather/ToGather/Screens/Core/Main/ViewModel/MainViewModel.swift
ToGather/ToGather/Screens/Core/SavingStatus/View/SavingStatusView.swift
ToGather/ToGather/Screens/Core/mainFriendSaving/FrSavingView.swift
ToGather/ToGather/ViewModels/UserViewModel.swift

- 전역으로 정의된 더미데이터를 struct로 묶음
- SavingStatusView, FrSavingStatusView에서 더미데이터를 인자로 받고 있어서 UserViewModel의 데이터를 받도록 수정

[Feat] 더미데이터 수정 &  더미데이터를 인자로 받는 경우를 수정

---

ToGather/ToGather/Screens/Onboarding/FriendAddition/UIComponent/PersonView.swift
ToGather/ToGather/Screens/Onboarding/FriendAddition/View/FriendAdditionView.swift

- ColorStyle 변경
- friendAdditionViewModel 재정의 제거

[Fix] 빌드오류 해결
